framework:
    messenger:
        # Konfiguracja transportu dla nieudanych wiadomości
        failure_transport: failed

        # Definicja transportów
        transports:
            # Transport dla przetwarzania obrazów (kompresja, konwersja, itp.)
            gtm_image_processing_queue:
                dsn: 'doctrine://default?queue_name=gtm_image_processing'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
            
            # Transport dla nieudanych wiadomości
            failed:
                dsn: 'doctrine://default?queue_name=failed_messages'

        # Mapowanie wiadomości do transportów
        routing:
            'App\Service\GraphicsToolsModule\Message\ImageProcessingMessage': gtm_image_processing_queue

        # Opcjonalnie: konfiguracja domyślnego command busu
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction

